[package]
name = "co3"

version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
authors = ["Marin Veršić <marin.versic101@gmail.com>"]
repository = "https://github.com/mversic/co3"
description = "Build C API from Rust"
keywords = ["FFI", "foreign", "dynamic", "linking", "ABI"]

categories = ["development-tools::ffi"]

[features]
default = ["alloc", "owned-as-ref"]

# Enable deriving `extern C` ABI. Macros made available are:
# - `#derive(ReprC)`/`#[extern_type]`
# - `#[export]`/`unsafe_extern_C!`/`unsafe_extern!`
derive = ["co3_derive"]

# Implements conversion traits for types from the `alloc` crate (e.g. `Box<T>` or `Vec<T>`).
alloc = []

# Encode (`Drop`) types as shared references instead of transferring ownership.
#
# With the notable exception of `Opaque` types which always carry ownership, this feature
# prevents ownership transfer of dynamically allocated memory across FFI boundary.
#
# # Performance Considerations
#
# This feature introduces otherwise unnecessary clone on decode paths of `Drop` types
owned-as-ref = []

# Enables reference types that don't maintain stable position in memory:
# - shared or mutable references to `Cloned` types (e.g. `&(u8,)`/`&mut (u8,)`)
# - shared or mutable slices of `Opaque` types (e.g. `&[Opaque]`/`&mut [Opaque]`)
# - `Transmuted` mutable references to non-robust types (e.g. `&mut bool`)
#
# # Performance Considerations
#
# This feature introduces the cost of cloning the referent on:
# - decode paths of `Cloned` references and `Opaque` slices
# - encode paths of `Cloned` and `Transmuted` references
#
# For `Transmuted` mutable references to non-robust types, the default behavior of encode paths uses
# clone + validation to prevent accidental UB from trap values set by the callee. Alternatively,
# these references can also be enabled through `unsafe-optimizations` which uses transmute-based
# encoding thus eliminating the clone and keeping the memory position of the reference stable.
unstable-refs = []

# Enables transmute-based encoding for mutable references to:
# - droppable transmuted types (e.g. `&mut Box<u32>`) where the callee can transfer ownership
# - non-robust transmuted types (e.g. `&mut bool`) where the callee can set a trap value
#
# Otherwise, the referent is cloned and validated before updating the reference, after calling the `extern "C"` function.
#
# # Safety
#
# When handing out mutable references to droppable types across FFI, it's possible for the callee
# to modify the referent to store values requiring custom Drop logic (such as calling allocator)
#
# When handing out mutable references to non-robust types across FFI, it's possible for the callee
# to modify the referent to store a trap representation thus causing UB.
#
# Use at your own discretion
unsafe-optimizations = []

# Enable integration with `getset` when deriving `extern C` ABI
# getset = ["derive", "co3_derive/getset"]

[dependencies]
co3_derive = { path = "derive", optional = true }

derive_more = { version = "2.1.1", features = ["display"] }
disjoint_impls = { path = "../disjoint_impls/" }
#disjoint_impls = "1.3.7"
impls = "1.0.3"

[dev-dependencies]
static_assertions = "1.1.0"
webassembly-test = "0.1.0"
#getset = "0.1.6"

[workspace]
resolver = "2"
members = ["derive"]

[[test]]
name = "abi"
required-features = ["alloc", "derive"]

[[test]]
name = "export"
required-features = ["alloc", "derive"]

[[test]]
name = "import"
required-features = ["alloc", "derive"]
