[workspace]
members = ["derive"]

[workspace.package]
version = "0.4.1"
edition = "2024"
license = "Apache-2.0"
authors = ["Marin Veršić <marin.versic101@gmail.com>"]

[package]
name = "co3"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

description = "Build C API from Rust"
repository = "https://github.com/mversic/co3"
categories = ["development-tools::ffi", "no-std"]
keywords = ["FFI", "foreign", "dynamic", "linking", "ABI"]

[features]
# Implements conversion traits for types from the `alloc` crate (e.g. `Box<T>` or `Vec<T>`).
alloc = ["rust-spec/alloc", "co3-derive?/alloc"]

# Enables:
# - deriving C-compatible representations with `#[derive(ReprC)]`
# - writing exports/extern FFI declarations via `ffi!`
derive = ["co3-derive"]

# Enables [allocator API](https://github.com/rust-lang/rust/issues/32838)
allocator-api = ["alloc"]

default = ["alloc", "derive"]

[dependencies]
co3-derive = { version = "0.4.1", path = "derive", optional = true }

rust-spec = { version = "0.3.1", default-features = false, features = ["derive"] }
disjoint_impls = "1.4.1"
impls = "1.0.3"

[dev-dependencies]
static_assertions = "1.1.0"
trybuild = "1.0.121"

[[test]]
name = "ui"
required-features = ["alloc", "derive"]

[[test]]
name = "abi"
required-features = ["alloc", "derive"]

[[test]]
name = "export"
required-features = ["alloc", "derive"]

[[test]]
name = "import"
required-features = ["alloc", "derive"]
