[package]
name = "co3-derive"

version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

description = "Derive macros for `CO3`"
repository = "https://github.com/mversic/co3/derive"

[lib]
proc-macro = true

[features]
alloc = []

[dependencies]
syn = { version = "3.0.4", features = ["full", "extra-traits", "visit", "visit-mut"] }
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.107"
manyhow = "0.13.0"
quote = "1.0.47"

[dev-dependencies]
co3 = { path = ".." }
