name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [system, wasm32]

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
        components: rustfmt, clippy
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Rust Format + Check + Lint
      run: |
        cargo fmt --all --check

        if [ "${{ matrix.target }}" = "wasm32" ]; then
          cargo clippy --workspace --tests --all-features --target wasm32-unknown-unknown
        else
          cargo clippy --workspace --tests --all-features
        fi

  test:
    runs-on: ubuntu-latest
    needs: static-analysis

    strategy:
      matrix:
        target: [system, wasm32]

    steps:
    - uses: actions/checkout@v6
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: wasm32-unknown-unknown
    - uses: Swatinem/rust-cache@v2
      with:
        key: ${{ matrix.target }}

    - name: Run tests
      run: |
        if [ "${{ matrix.target }}" = "wasm32" ]; then
          cargo test --workspace --all-features --target wasm32-unknown-unknown
        else
          cargo test --workspace --all-features
        fi

